language: php

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-version-1.next as 1.26.0"'
        - LARAVEL_VERSION='"5.6.*"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-master as 1.26.0"'
        - LARAVEL_VERSION='"5.6.*"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-version-1.next as 1.26.3"'
        - LARAVEL_VERSION='"5.8.*"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-master as 1.26.3"'
        - LARAVEL_VERSION='"5.8.*"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-version-1.next as 1.26.0"'
        - LARAVEL_VERSION='"5.6.*"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 1.26.0"'
        - LARAVEL_VERSION='"5.6.*"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-version-1.next as 1.26.3"'
        - LARAVEL_VERSION='"5.8.*"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 1.26.3"'
        - LARAVEL_VERSION='"5.8.*"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 2.0"'
        - LARAVEL_VERSION='"6.0.*"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 2.0"'
        - LARAVEL_VERSION='"6.18.*"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 2.17"'
        - LARAVEL_VERSION='"7.0.*"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 2.17"'
        - LARAVEL_VERSION='"7.9.*"'
    - php: 7.3
      env:
        - CARBON_VERSION='"dev-version-1.next as 1.26.0"'
        - LARAVEL_VERSION='"5.6.*"'
    - php: 7.3
      env:
        - CARBON_VERSION='"dev-master as 1.26.0"'
        - LARAVEL_VERSION='"5.6.*"'
    - php: 7.3
      env:
        - CARBON_VERSION='"dev-version-1.next as 1.26.3"'
        - LARAVEL_VERSION='"5.8.*"'
    - php: 7.3
      env:
        - CARBON_VERSION='"dev-master as 1.26.3"'
        - LARAVEL_VERSION='"5.8.*"'
    - php: 7.3
      env:
        - CARBON_VERSION='"dev-master as 2.0"'
        - LARAVEL_VERSION='"6.0.*"'
    - php: 7.3
      env:
        - CARBON_VERSION='"dev-master as 2.0"'
        - LARAVEL_VERSION='"6.18.*"'
    - php: 7.3
      env:
        - CARBON_VERSION='"dev-master as 2.17"'
        - LARAVEL_VERSION='"7.0.*"'
    - php: 7.3
      env:
        - CARBON_VERSION='"dev-master as 2.17"'
        - LARAVEL_VERSION='"7.9.*"'
    - php: 7.3
      env:
        - CARBON_VERSION='"dev-master as 2.17"'
        - LARAVEL_VERSION='"dev-master as 8.0"'
    - php: 7.4snapshot
      env:
        - CARBON_VERSION='"dev-version-1.next as 1.26.0"'
        - LARAVEL_VERSION='"5.6.*"'
    - php: 7.4snapshot
      env:
        - CARBON_VERSION='"dev-master as 1.26.0"'
        - LARAVEL_VERSION='"5.6.*"'
    - php: 7.4snapshot
      env:
        - CARBON_VERSION='"dev-version-1.next as 1.26.3"'
        - LARAVEL_VERSION='"5.8.*"'
    - php: 7.4snapshot
      env:
        - CARBON_VERSION='"dev-master as 1.26.3"'
        - LARAVEL_VERSION='"5.8.*"'
    - php: 7.4snapshot
      env:
        - CARBON_VERSION='"dev-master as 2.0"'
        - LARAVEL_VERSION='"6.0.*"'
    - php: 7.4snapshot
      env:
        - CARBON_VERSION='"dev-master as 2.0"'
        - LARAVEL_VERSION='"6.18.*"'
    - php: 7.4snapshot
      env:
        - CARBON_VERSION='"dev-master as 2.17"'
        - LARAVEL_VERSION='"7.0.*"'
    - php: 7.4snapshot
      env:
        - CARBON_VERSION='"dev-master as 2.17"'
        - LARAVEL_VERSION='"7.9.*"'
    - php: 7.4snapshot
      env:
        - CARBON_VERSION='"dev-master as 2.17"'
        - LARAVEL_VERSION='"dev-master as 8.0"'

before_script:
  - travis_retry composer self-update
  - travis_retry php setVersions.php $CARBON_VERSION $LARAVEL_VERSION
  - travis_retry composer update -o --no-interaction --prefer-stable $COMPOSER_PLATFORM_REQS

script:
  - vendor/bin/phpunit

notifications:
  slack:
    secure: mdZBxjp18TYD4hOXKrj2mayveaUBj2fcgiVb1LOv1fiuonzhNwT5I5n795BNGpl1z76I8ZzD3MICbvigXs8QGMBkTnCriSEZNuyQUlAR972q+h02HmKM/j0d90S3tGbPh6PFGh0oo7ZCt0TAlHtNTGL0uyOwzJ26A+Sa5zA8HzN+y44KXTyMYRE/RXDkKB8460W+UFOVXsFw3pdXqeW6CbQY4A8hR8F0veBThfqrE/qXtmQ0MR97uuaDQDbJAiJuVe3DzIOcAdYwuqYbm3sgsomqsXONX7LyrrqXPguNDyM7XwkZUP6t9Nqvxz94HIJkYWASFNgOyysxOYqhgtAG7/xkT77D63IzxcsxLtfNSzOJwaP7xE3YHog082MR0ywdpZpjklmDdPhhiDfGaGRSHGJCqEMcW4QjFibLm3pnvxXoeTyY4Zx0hkCRqDlTYq9IMX6i3fVF4dZ+egOSJrd9BDXlnkyNy2C3z/5Ee6hfVoD53FT4l8zvRc+ip2tFQOzE1O81o8OYHOsF4DfcE0u1B/+ZeYihuFbJ8DMIBv8bUlZ76sQLQD0FAPzeKURDB2lTlUFODUH8ewPEuGbH6Bbao5bFoeWKvC6xTCuanpeU1xwJrzSvzMljqcEyZmOoqST776wCwS/qjY9yh8344VTZYHqGVY/L5DxjTbvSKpyHj2k=
