language: php

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.4
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.0.35"'
    - php: 5.5
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.0.35"'
    - php: 5.5
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.1.46"'
    - php: 5.5
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.2.45"'
    - php: 5.6
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.0.35"'
    - php: 5.6
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.1.46"'
    - php: 5.6
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.2.45"'
    - php: 5.6
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.3.31"'
    - php: 5.6
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.4.36"'
    - php: 7.0
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.0.35"'
    - php: 7.0
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.1.46"'
    - php: 7.0
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.2.45"'
    - php: 7.0
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.3.31"'
    - php: 7.0
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.4.36"'
    - php: 7.0
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.5.40"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.0.35"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.1.46"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.2.45"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.3.31"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.4.36"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.5.40"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.6.26"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-version-2.0 as 1.25.0"'
        - LARAVEL_VERSION='"5.6.26"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-master as 1.27.0"'
        - LARAVEL_VERSION='"dev-master as 5.7"'
    - php: 7.1
      env:
        - CARBON_VERSION='"dev-version-2.0 as 1.27.0"'
        - LARAVEL_VERSION='"dev-master as 5.7"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.0.35"'
        - COMPOSER_PLATFORM_REQS='--ignore-platform-reqs'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.1.46"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.2.45"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.3.31"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.4.36"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.5.40"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 1.25.0"'
        - LARAVEL_VERSION='"5.6.26"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-version-2.0 as 1.25.0"'
        - LARAVEL_VERSION='"5.6.26"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-master as 1.27.0"'
        - LARAVEL_VERSION='"dev-master as 5.7"'
    - php: 7.2
      env:
        - CARBON_VERSION='"dev-version-2.0 as 1.27.0"'
        - LARAVEL_VERSION='"dev-master as 5.7"'

before_script:
  - travis_retry composer self-update
  - travis_retry php setVersions.php $CARBON_VERSION $LARAVEL_VERSION
  - travis_retry composer update -o --no-interaction --prefer-stable $COMPOSER_PLATFORM_REQS

script:
  - vendor/bin/phpunit
